/* DH SHOP & DELIVERY — ADMIN.JS v20 */
const SUPABASE_URL="https://ocmvthymdjkrhmdyieim.supabase.co";
const SUPABASE_KEY="sb_publishable_OnchBsvLE3RVA-EualXSSA_pfVvFpTW";
const SESSION_KEY="dh_admin_session";
let session=null,products=[],orders=[],currentOrderFilter="all",editingProductId=null;
const $=id=>document.getElementById(id);
const first=(...ids)=>ids.map($).find(Boolean)||null;
const val=ids=>{const e=first(...ids);return e?e.value.trim():""};
const setVal=(ids,v)=>{const e=first(...ids);if(e)e.value=v??""};
const setText=(ids,v)=>{const e=first(...ids);if(e)e.textContent=v};
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");
const money=v=>Number(v||0).toLocaleString("fr-FR")+" FCFA";
const notify=(m,t="info")=>{console.log(m);const e=first("message","adminMessage","productMessage","whatsappMessage");if(e){e.textContent=m;e.style.color=t==="error"?"#b91c1c":t==="success"?"#15803d":""}};
const show=(e,b)=>{if(e)e.style.display=b?"":"none"};
function saveSession(x){session=x;localStorage.setItem(SESSION_KEY,JSON.stringify(x))}
function clearSession(){session=null;localStorage.removeItem(SESSION_KEY)}
function storedSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||"null")}catch{return null}}
async function api(path,opt={}){const h=new Headers(opt.headers||{});h.set("apikey",SUPABASE_KEY);h.set("Authorization",`Bearer ${session?.access_token||SUPABASE_KEY}`);if(opt.body&&!(opt.body instanceof FormData)&&!h.has("Content-Type"))h.set("Content-Type","application/json");const c=new AbortController(),t=setTimeout(()=>c.abort(),15000);try{const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...opt,headers:h,signal:c.signal});const tx=await r.text();let d=null;try{d=tx?JSON.parse(tx):null}catch{d=tx}if(!r.ok)throw new Error(d?.message||d?.error_description||d?.hint||d?.details||(typeof d==="string"?d:`Erreur HTTP ${r.status}`));return d}finally{clearTimeout(t)}}
async function login(){const email=val(["email","loginEmail","adminEmail"]),p=first("password","loginPassword","adminPassword"),password=p?.value||"",b=first("loginBtn","loginButton");if(!email||!password)return notify("❌ Entrez votre email et votre mot de passe.","error");try{if(b)b.disabled=true;notify("⏳ Connexion...");const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:SUPABASE_KEY,"Content-Type":"application/json"},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d?.error_description||d?.msg||"Connexion refusée.");saveSession(d);await verifyAdmin();showAdmin();await loadAll();notify("✅ Connexion réussie.","success")}catch(e){clearSession();showLogin();notify("❌ "+e.message,"error")}finally{if(b)b.disabled=false}}
async function verifyAdmin(){const r=await api(`admin_users?select=user_id&user_id=eq.${encodeURIComponent(session.user.id)}`);if(!Array.isArray(r)||!r.length){clearSession();throw new Error("Ce compte n'est pas autorisé comme administrateur.")}}
function logout(){clearSession();products=[];orders=[];showLogin()}
function showLogin(){show(first("loginBox","login"),true);show(first("dashboard","adminDashboard"),false)}
function showAdmin(){show(first("loginBox","login"),false);show(first("dashboard","adminDashboard"),true)}
async function loadProducts(){const r=await api("products?select=*&order=created_at.desc");products=Array.isArray(r)?r:[];renderProducts(products);updateStats(products);return products}
function updateStats(a){setText(["productCount","productsCount"],a.length);setText(["availableCount","availableProducts"],a.filter(p=>p.available!==false&&Number(p.stock||0)>0).length);setText(["outCount","outOfStockCount"],a.filter(p=>p.available===false||Number(p.stock||0)<=0).length)}
function renderProducts(a){const c=first("productList","productsList","adminProductList");if(!c)return;if(!a.length){c.innerHTML="<div>Aucun produit.</div>";return}c.innerHTML=a.map(p=>`<div style="display:flex;gap:12px;align-items:center;padding:12px 0;border-bottom:1px solid #ddd"><div>${p.image_url?`<img src="${esc(p.image_url)}" style="width:64px;height:64px;object-fit:cover;border-radius:10px">`:`📦`}</div><div style="flex:1"><strong>${esc(p.name)}</strong><div>${money(p.price)}</div><small>Stock: ${Number(p.stock||0)}</small></div><button type="button" class="edit-product-btn" data-id="${p.id}">✏️</button><button type="button" class="delete-product-btn" data-id="${p.id}">🗑️</button></div>`).join("");c.querySelectorAll(".edit-product-btn").forEach(b=>b.onclick=()=>editProduct(b.dataset.id));c.querySelectorAll(".delete-product-btn").forEach(b=>b.onclick=()=>deleteProduct(b.dataset.id))}
function formData(){const av=first("productAvailable","available");return{name:val(["productName","name"]),category:val(["productCategory","category"])||"autres",price:Number(val(["productPrice","price"])||0),description:val(["productDescription","description"]),stock:Number(val(["productStock","stock"])||0),available:av?av.checked:true,badge:val(["productBadge","badge"])||null}}
function fillProduct(p){setVal(["productName","name"],p.name);setVal(["productCategory","category"],p.category);setVal(["productPrice","price"],p.price);setVal(["productDescription","description"],p.description);setVal(["productStock","stock"],p.stock);setVal(["productBadge","badge"],p.badge||"");const a=first("productAvailable","available");if(a)a.checked=p.available!==false;editingProductId=p.id;const b=first("addProductBtn","saveProductBtn");if(b)b.textContent="💾 Enregistrer les modifications"}
function editProduct(id){const p=products.find(x=>String(x.id)===String(id));if(p)fillProduct(p)}
function resetProductForm(){editingProductId=null;const f=$("productForm");if(f)f.reset();const b=first("addProductBtn","saveProductBtn");if(b)b.textContent="➕ Ajouter le produit"}
async function uploadProductImage(file){if(!file.type.startsWith("image/"))throw new Error("Le fichier doit être une image.");if(file.size>8*1024*1024)throw new Error("Image trop lourde. Maximum 8 Mo.");const name=file.name.toLowerCase().replace(/[^a-z0-9.]+/g,"-");const path=`${Date.now()}-${name}`;const r=await fetch(`${SUPABASE_URL}/storage/v1/object/product-images/${path}`,{method:"POST",headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${session.access_token}`,"Content-Type":file.type||"application/octet-stream","x-upsert":"true"},body:file});if(!r.ok)throw new Error(await r.text()||"Échec de l'envoi de l'image.");return `${SUPABASE_URL}/storage/v1/object/public/product-images/${path}`}
async function saveProduct(e){e?.preventDefault();const d=formData();if(!d.name)return notify("❌ Le nom du produit est obligatoire.","error");if(d.price<0)return notify("❌ Prix invalide.","error");const b=first("addProductBtn","saveProductBtn"),fi=first("productImage","image","imageFile"),file=fi?.files?.[0];try{if(b)b.disabled=true;notify("⏳ Enregistrement du produit...");const old=editingProductId?products.find(p=>String(p.id)===String(editingProductId)):null;const payload={name:d.name,category:d.category,price:d.price,description:d.description,stock:d.stock,available:d.available&&d.stock>0,badge:d.badge};if(file)payload.image_url=await uploadProductImage(file);else if(old?.image_url)payload.image_url=old.image_url;if(editingProductId)await api(`products?id=eq.${editingProductId}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify(payload)});else await api("products",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify(payload)});notify("✅ Produit enregistré.","success");resetProductForm();await loadProducts()}catch(e2){notify("❌ "+e2.message,"error")}finally{if(b)b.disabled=false}}
async function deleteProduct(id){const p=products.find(x=>String(x.id)===String(id));if(!p||!confirm(`Supprimer « ${p.name} » ?`))return;try{await api(`products?id=eq.${id}`,{method:"DELETE"});notify("✅ Produit supprimé.","success");await loadProducts()}catch(e){notify("❌ "+e.message,"error")}}
function normalizeStatus(s){s=String(s||"nouvelle").toLowerCase();if(["new","nouvelle","nouvelles","pending"].includes(s))return"nouvelle";if(["preparation","en préparation","en preparation","processing"].includes(s))return"preparation";if(["delivery","en livraison","livraison","shipping"].includes(s))return"livraison";if(["delivered","livrée","livree","livrées"].includes(s))return"livree";if(["cancelled","canceled","annulée","annulee"].includes(s))return"annulee";return s}
function statusLabel(s){return({nouvelle:"NOUVELLE",preparation:"EN PRÉPARATION",livraison:"EN LIVRAISON",livree:"LIVRÉE",annulee:"ANNULÉE"}[normalizeStatus(s)]||String(s||"NOUVELLE").toUpperCase())}
function dateFmt(d){try{return new Date(d).toLocaleString("fr-FR",{dateStyle:"short",timeStyle:"short"})}catch{return d||""}}
function itemsText(x){if(!x)return"Articles non détaillés";if(typeof x==="string")try{x=JSON.parse(x)}catch{return x}return Array.isArray(x)?x.map(i=>`${i.name||i.product_name||"Produit"} × ${i.quantity??i.qty??1}`).join(" • "):"Articles non détaillés"}
async function loadOrders(){const c=first("ordersList","orderList","commandesList","ordersContainer");if(c)c.innerHTML='<div style="padding:20px;text-align:center">⏳ Chargement des commandes…</div>';try{const r=await api("orders?select=*&order=created_at.desc");orders=Array.isArray(r)?r:[];renderOrders();setText(["orderCount","ordersCount","commandCount","commandesCount"],orders.length);return orders}catch(e){orders=[];if(c)c.innerHTML=`<div style="padding:20px;color:#b91c1c;text-align:center">❌ Impossible de charger les commandes.<br><small>${esc(e.message)}</small></div>`;console.error(e);return[]}}
function renderOrders(){const c=first("ordersList","orderList","commandesList","ordersContainer");if(!c)return;const a=currentOrderFilter==="all"?orders:orders.filter(o=>normalizeStatus(o.status)===currentOrderFilter);if(!a.length){c.innerHTML='<div style="padding:25px;text-align:center;color:#666">Aucune commande dans cette catégorie.</div>';return}c.innerHTML=a.map(o=>{const s=normalizeStatus(o.status);return`<article style="border:1px solid #ddd;border-radius:14px;padding:15px;margin:12px 0;background:#fff"><div style="display:flex;justify-content:space-between;gap:8px"><div><strong>Commande #${esc(o.id)}</strong><div style="font-size:13px;color:#666">${esc(dateFmt(o.created_at))}</div></div><b>${esc(statusLabel(s))}</b></div><div style="margin-top:10px;line-height:1.6"><div>👤 <strong>Client :</strong> ${esc(o.customer_name||"—")}</div><div>📞 <strong>Téléphone :</strong> ${esc(o.phone||"—")}</div><div>📍 <strong>Adresse :</strong> ${esc(o.address||"—")}</div><div>💳 <strong>Paiement :</strong> ${esc(o.payment_method||"—")}</div><div>🛍️ <strong>Articles :</strong> ${esc(itemsText(o.items))}</div><div style="font-size:18px;font-weight:700">💰 ${money(o.total)}</div></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:12px"><select class="order-status-select" data-id="${esc(o.id)}"><option value="nouvelle" ${s==="nouvelle"?"selected":""}>NOUVELLE</option><option value="preparation" ${s==="preparation"?"selected":""}>EN PRÉPARATION</option><option value="livraison" ${s==="livraison"?"selected":""}>EN LIVRAISON</option><option value="livree" ${s==="livree"?"selected":""}>LIVRÉE</option><option value="annulee" ${s==="annulee"?"selected":""}>ANNULÉE</option></select><button type="button" class="delete-order-btn" data-id="${esc(o.id)}">🗑️ Supprimer</button></div></article>`}).join("");c.querySelectorAll(".order-status-select").forEach(s=>s.onchange=()=>updateOrderStatus(s.dataset.id,s.value));c.querySelectorAll(".delete-order-btn").forEach(b=>b.onclick=()=>deleteOrder(b.dataset.id))}
async function updateOrderStatus(id,status){try{await api(`orders?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status})});const o=orders.find(x=>String(x.id)===String(id));if(o)o.status=status;renderOrders();notify("✅ Statut mis à jour.","success")}catch(e){notify("❌ "+e.message,"error");await loadOrders()}}
async function deleteOrder(id){if(!confirm("Supprimer définitivement cette commande ?"))return;try{await api(`orders?id=eq.${encodeURIComponent(id)}`,{method:"DELETE"});notify("✅ Commande supprimée.","success");await loadOrders()}catch(e){notify("❌ "+e.message,"error")}}
function setupOrderFilter(){const s=first("orderFilter","ordersFilter","commandesFilter","statusFilter");if(!s)return;s.onchange=()=>{const m={all:"all","":"all",new:"nouvelle",nouvelle:"nouvelle",preparation:"preparation",livraison:"livraison",livree:"livree",annulee:"annulee"};currentOrderFilter=m[s.value]||s.value||"all";renderOrders()}}
async function loadSettings(){try{const r=await api("shop_settings?id=eq.1&select=*");const x=r?.[0];if(!x)return;setVal(["shopName","shopNameInput"],x.shop_name);setVal(["whatsappNumber","whatsapp","whatsappInput"],x.whatsapp_number);setVal(["currency","currencyInput"],x.currency)}catch(e){console.warn(e)}}
async function saveWhatsappNumber(){const i=first("whatsappNumber","whatsapp","whatsappInput"),m=$("whatsappMessage"),b=$("saveWhatsappBtn");if(!i)return;const n=i.value.trim().replace(/\s+/g,"");if(!/^[0-9]{8,15}$/.test(n)){if(m)m.textContent="❌ Numéro invalide. Exemple : 22792617092";return}try{if(b)b.disabled=true;if(m)m.textContent="⏳ Enregistrement...";await api("shop_settings?id=eq.1",{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({whatsapp_number:n})});if(m)m.textContent="✅ Numéro WhatsApp enregistré avec succès."}catch(e){if(m)m.textContent="❌ Erreur : "+e.message}finally{if(b)b.disabled=false}}
async function loadAll(){await Promise.allSettled([loadProducts(),loadOrders(),loadSettings()])}
function setupEvents(){const l=first("loginBtn","loginButton");if(l)l.onclick=login;const o=first("logoutBtn","logoutButton");if(o)o.onclick=logout;const r=first("refreshOrdersBtn","refreshOrders","actualiserOrders","refreshOrdersButton");if(r)r.onclick=loadOrders;const all=first("refreshBtn","actualiserBtn");if(all)all.onclick=loadAll;const f=$("productForm");if(f)f.addEventListener("submit",saveProduct);const add=$("addProductBtn");if(add&&!f)add.onclick=saveProduct;const w=$("saveWhatsappBtn");if(w)w.onclick=saveWhatsappNumber;const cancel=first("cancelProductBtn","cancelEditBtn","resetProductBtn");if(cancel)cancel.onclick=resetProductForm;setupOrderFilter();const p=first("password","loginPassword","adminPassword");if(p)p.onkeydown=e=>{if(e.key==="Enter")login()}}
async function init(){setupEvents();session=storedSession();if(!session?.access_token||!session?.user?.id)return showLogin();try{await verifyAdmin();showAdmin();await loadAll()}catch(e){clearSession();showLogin()}}
document.addEventListener("DOMContentLoaded",init);
