(()=>{"use strict";
const URL="https://ocmvthymdjkrhmdyieim.supabase.co",KEY="sb_publishable_OnchBsvLE3RVA-EualXSSA_pfVvFpTW";
const S={products:[],filtered:[],cart:JSON.parse(localStorage.getItem("dhCart")||"[]"),cat:"all",q:"",sort:"newest",wa:"22792617092"};
const $=x=>document.getElementById(x),money=n=>Number(n||0).toLocaleString("fr-FR")+" FCFA";
const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&#039;","'":"&#039;"}[c]));
async function api(path,opt={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(URL+"/rest/v1/"+path,{...opt,signal:c.signal,headers:{apikey:KEY,Authorization:"Bearer "+KEY,"Content-Type":"application/json",...(opt.headers||{})}}),txt=await r.text();let d=null;try{d=txt?JSON.parse(txt):null}catch{}if(!r.ok)throw Error(d?.message||d?.hint||txt||"Erreur HTTP "+r.status);return d}finally{clearTimeout(t)}}
function save(){localStorage.setItem("dhCart",JSON.stringify(S.cart))}
function total(){return S.cart.reduce((a,i)=>a+i.price*i.qty,0)}
function badge(){$("cartCount").textContent=S.cart.reduce((a,i)=>a+i.qty,0);$("cartTotal").textContent=money(total());$("checkoutTotal").textContent=money(total())}
async function settings(){try{const r=await api("shop_settings?select=whatsapp_number&id=eq.1");if(r?.[0]?.whatsapp_number)S.wa=String(r[0].whatsapp_number).replace(/\D/g,"")}catch(e){console.warn(e)}}
function cats(){return [...new Set(S.products.map(p=>String(p.category||"Autres").trim()).filter(Boolean))]}
function firstProductFor(c){return S.products.find(p=>String(p.category||"Autres").trim()===c&&p.image_url)||S.products.find(p=>p.image_url)}
function heroImage(){const p=S.products.find(x=>String(x.category||"").toLowerCase().includes("chauss"))||S.products.find(x=>x.image_url);if(p?.image_url){$("hero").style.backgroundImage=`url("${p.image_url.replace(/"/g,"%22")}")`}}
function categoryData(){return cats().map(c=>({name:c,count:S.products.filter(p=>String(p.category||"Autres").trim()===c).length,img:firstProductFor(c)?.image_url||""}))}
function renderCategories(){const data=categoryData();
$("homeCategories").innerHTML=data.map(c=>`<a class="home-cat" href="#boutique" data-cat-link="${esc(c.name)}">${c.img?`<img src="${esc(c.img)}" alt="">`:""}<div class="cat-text"><span>${esc(c.name)}</span><span class="cat-arrow">→</span></div></a>`).join("");
$("categoryTabs").innerHTML=`<button class="category-tab ${S.cat==="all"?"active":""}" data-cat="all">Tout</button>`+data.map(c=>`<button class="category-tab ${S.cat===c.name?"active":""}" data-cat="${esc(c.name)}">${esc(c.name)}</button>`).join("");
$("sideCategories").innerHTML=data.map(c=>`<a href="#boutique" data-side-cat="${esc(c.name)}" data-close-menu><span>›</span>${esc(c.name)}</a>`).join("");
document.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>{S.cat=b.dataset.cat;renderCategories();filter();location.hash="boutique";});
document.querySelectorAll("[data-cat-link],[data-side-cat]").forEach(b=>b.onclick=()=>{S.cat=b.dataset.catLink||b.dataset.sideCat;renderCategories();filter();closeMenu();});
}
function filter(){let a=[...S.products];if(S.cat!=="all")a=a.filter(p=>String(p.category||"Autres").trim()===S.cat);if(S.q)a=a.filter(p=>`${p.name} ${p.description||""} ${p.category||""}`.toLowerCase().includes(S.q.toLowerCase()));if(S.sort==="price-asc")a.sort((x,y)=>x.price-y.price);if(S.sort==="price-desc")a.sort((x,y)=>y.price-x.price);if(S.sort==="name")a.sort((x,y)=>String(x.name).localeCompare(String(y.name),"fr"));S.filtered=a;render()}
function img(p){return p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}" onerror="this.style.display='none'">`:`<span class="placeholder">✦</span>`}
function card(p){return `<article class="card">${p.badge?`<span class="badge">${esc(p.badge)}</span>`:""}<div class="pic" data-view="${p.id}">${img(p)}</div><div class="info"><h3>${esc(p.name)}</h3><p>${esc(p.category||"Produit")}</p><div class="price">${money(p.price)}</div><div class="cardBtns"><button class="add" data-add="${p.id}" aria-label="Ajouter">+</button></div></div></article>`}
function render(){const g=$("productGrid");g.innerHTML=S.filtered.length?S.filtered.map(card).join(""):'<div class="empty">Aucun produit ne correspond à votre recherche.</div>';bindCards();renderFeatured()}
function renderFeatured(){const g=$("featuredGrid");const a=S.products.slice(0,4);g.innerHTML=a.length?a.map(card).join(""):'<div class="empty">Aucun produit disponible.</div>';bindCards(g)}
function bindCards(root=document){root.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>view(b.dataset.add));root.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>view(b.dataset.view))}
function find(id){return S.products.find(p=>String(p.id)===String(id))}
function variantList(v){if(Array.isArray(v))return v.map(x=>String(x).trim()).filter(Boolean);if(typeof v==="string"){try{const a=JSON.parse(v);if(Array.isArray(a))return a.map(x=>String(x).trim()).filter(Boolean)}catch{}const s=v.trim();if(/^\d+(?:\.\s*\d+)+$/.test(s))return s.split(/\s*\.\s*/).map(x=>x.trim()).filter(Boolean);return s.split(/[,;\n|/]+/).map(x=>x.trim()).filter(Boolean)}return[]}
function variantOptions(p){const sizes=variantList(p.sizes),colors=variantList(p.colors);let h="";if(sizes.length)h+=`<label class="variant-label">Taille<select id="modalSize"><option value="">Choisir une taille</option>${sizes.map(x=>`<option>${esc(x)}</option>`).join("")}</select></label>`;if(colors.length)h+=`<label class="variant-label">Couleur<select id="modalColor"><option value="">Choisir une couleur</option>${colors.map(x=>`<option>${esc(x)}</option>`).join("")}</select></label>`;return h}
function add(id,size="",color=""){const p=find(id);if(!p)return;const key=`${p.id}|${size}|${color}`,i=S.cart.find(x=>x.key===key);if(i)i.qty++;else S.cart.push({key,id:p.id,name:p.name,price:Number(p.price),image_url:p.image_url||"",qty:1,size,color});save();cart();openCart()}
function cart(){const b=$("cartItems");if(!S.cart.length)b.innerHTML='<div class="empty">Votre panier est vide.</div>';else b.innerHTML=S.cart.map(i=>`<div class="row"><div class="thumb">${i.image_url?`<img src="${esc(i.image_url)}">`:"✦"}</div><div><h4>${esc(i.name)}</h4><small>${money(i.price)}${i.size?`<br>Taille : ${esc(i.size)}`:""}${i.color?`<br>Couleur : ${esc(i.color)}`:""}</small><div class="qty"><button data-m="${esc(i.key)}">−</button><b>${i.qty}</b><button data-p="${esc(i.key)}">+</button></div></div><button class="remove" data-r="${esc(i.key)}">Supprimer</button></div>`).join("");b.querySelectorAll("[data-m]").forEach(x=>x.onclick=()=>qty(x.dataset.m,-1));b.querySelectorAll("[data-p]").forEach(x=>x.onclick=()=>qty(x.dataset.p,1));b.querySelectorAll("[data-r]").forEach(x=>x.onclick=()=>remove(x.dataset.r));badge()}
function qty(key,d){const i=S.cart.find(x=>x.key===key);if(i)i.qty+=d;if(i?.qty<=0)remove(key);else{save();cart()}}
function remove(key){S.cart=S.cart.filter(x=>x.key!==key);save();cart()}
function openCart(){$("cartDrawer").classList.add("open");$("overlay").classList.add("open")}
function closeCart(){$("cartDrawer").classList.remove("open");$("overlay").classList.remove("open")}
function view(id){const p=find(id);if(!p)return;$("modalContent").innerHTML=`<div class="modalProduct"><div>${img(p)}</div><div><em>${esc(p.category||"PRODUIT")}</em><h2>${esc(p.name)}</h2><p>${esc(p.description||"Produit DH Shop & Delivery.")}</p><h3>${money(p.price)}</h3><div class="modal-stock">Disponible en stock</div>${variantOptions(p)}<button class="red-btn full" id="modalAdd">Ajouter au panier</button></div></div>`;$("modalAdd").onclick=()=>{const size=$("modalSize")?.value||"",color=$("modalColor")?.value||"";if($("modalSize")&&!size)return alert("Veuillez choisir une taille.");if($("modalColor")&&!color)return alert("Veuillez choisir une couleur.");$("productModal").classList.remove("open");add(id,size,color)};$("productModal").classList.add("open")}
function makeRef(){return"DH-"+Date.now().toString().slice(-8)}
async function order(e){e.preventDefault();if(!S.cart.length)return alert("Votre panier est vide.");const m=$("checkoutMessage"),btn=e.submitter;btn.disabled=true;m.textContent="Enregistrement…";const ref=makeRef(),o={customer_name:$("customerName").value.trim(),phone:$("customerPhone").value.trim(),address:$("customerAddress").value.trim(),items:S.cart,total:total(),payment_method:$("paymentMethod").value,status:"Nouvelle",reference:ref};try{await api("orders",{method:"POST",headers:{"Prefer":"return=minimal"},body:JSON.stringify(o)});const lines=S.cart.map(i=>`• ${i.name}${i.size?` — Taille ${i.size}`:""}${i.color?` — ${i.color}`:""} x${i.qty} — ${money(i.price*i.qty)}`).join("\n"),text=`🛍️ *NOUVELLE COMMANDE — DH SHOP & DELIVERY*\n\nRéférence : *${ref}*\nNom : ${o.customer_name}\nTéléphone : ${o.phone}\nAdresse : ${o.address}\nPaiement : ${o.payment_method}\n\n${lines}\n\n*TOTAL : ${money(o.total)}*`,wa=`https://wa.me/${S.wa}?text=${encodeURIComponent(text)}`;S.cart=[];save();cart();$("checkoutForm").reset();m.innerHTML=`✅ Commande enregistrée : <b>${ref}</b><br><small>Conservez cette référence pour suivre votre commande.</small><br><a class="red-btn" target="_blank" href="${wa}">Continuer sur WhatsApp</a>`}catch(x){m.textContent="❌ "+(x.message||"Erreur")}finally{btn.disabled=false}}
async function track(e){e.preventDefault();const v=$("trackingInput").value.trim().toUpperCase(),r=$("trackingResult");r.textContent="Recherche…";if(!/^DH-[A-Z0-9]+$/.test(v)){r.textContent="Entrez une référence comme DH-07048624.";return}try{const a=await api("rpc/track_order",{method:"POST",body:JSON.stringify({p_reference:v})});const row=Array.isArray(a)?a[0]:a;r.innerHTML=row?`<strong>Commande ${esc(row.reference)}</strong><br>Statut : <b>${esc(row.status||"En traitement")}</b><br><small>${row.created_at?new Date(row.created_at).toLocaleString("fr-FR"):""}</small>`:"Commande introuvable."}catch(x){console.error(x);r.textContent="Impossible de vérifier la commande pour le moment."}}
function openMenu(){$("sideMenu").classList.add("open");$("drawerBackdrop").classList.add("open");$("sideMenu").setAttribute("aria-hidden","false")}
function closeMenu(){$("sideMenu").classList.remove("open");$("drawerBackdrop").classList.remove("open");$("sideMenu").setAttribute("aria-hidden","true")}
function activeNav(){let h=location.hash.replace("#","")||"accueil";if(h==="panier")h="boutique";document.querySelectorAll(".bottom-nav a").forEach(a=>a.classList.toggle("active",a.dataset.nav===h))}
function goHash(){activeNav();if(location.hash==="#panier"){openCart();history.replaceState(null,"","#boutique")}}
async function init(){ $("menuBtn").onclick=openMenu;$("closeMenu").onclick=closeMenu;$("drawerBackdrop").onclick=closeMenu;$("cartBtn").onclick=openCart;$("bottomCart").onclick=e=>{e.preventDefault();openCart()};$("closeCart").onclick=closeCart;$("overlay").onclick=closeCart;$("closeProductModal").onclick=()=>$("productModal").classList.remove("open");$("closeCheckoutModal").onclick=()=>$("checkoutModal").classList.remove("open");$("checkoutBtn").onclick=()=>{if(!S.cart.length)return alert("Votre panier est vide.");closeCart();$("checkoutModal").classList.add("open")};$("checkoutForm").onsubmit=order;$("trackingForm").onsubmit=track;$("searchInput").oninput=e=>{S.q=e.target.value;filter()};$("sortSelect").onchange=e=>{S.sort=e.target.value;filter()};document.querySelectorAll("[data-close-menu]").forEach(a=>a.onclick=closeMenu);window.addEventListener("hashchange",goHash);cart();await settings();$("sideWhatsApp").textContent=S.wa?`+${S.wa}`:"Commandez directement";$("contactPhoneText").textContent=S.wa?`+${S.wa}`:"—";$("contactWhatsapp").href=`https://wa.me/${S.wa}`;$("contactPhone").href=`tel:+${S.wa}`;try{const r=await api("products?select=*&order=created_at.desc");S.products=(r||[]).filter(p=>p.available!==false&&Number(p.stock??1)>0);heroImage();renderCategories();filter();$("productStatus").textContent=S.products.length?`${S.products.length} produit(s) disponibles`:"Aucun produit disponible pour le moment."}catch(e){console.error(e);$("productStatus").textContent="Impossible de charger les produits.";renderCategories();filter()}goHash()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
