(()=>{"use strict";
const URL="https://ocmvthymdjkrhmdyieim.supabase.co",KEY="sb_publishable_OnchBsvLE3RVA-EualXSSA_pfVvFpTW";
const S={products:[],filtered:[],cart:JSON.parse(localStorage.getItem("dhCart")||"[]"),cat:"all",q:"",sort:"newest",wa:"22792617092",page:"accueil",hero:0};
const $=x=>document.getElementById(x),money=n=>Number(n||0).toLocaleString("fr-FR")+" FCFA";
const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&#039;","'":"&#039;"}[c]));
async function api(path,opt={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(URL+"/rest/v1/"+path,{...opt,signal:c.signal,headers:{apikey:KEY,Authorization:"Bearer "+KEY,"Content-Type":"application/json",...(opt.headers||{})}}),txt=await r.text();let d=null;try{d=txt?JSON.parse(txt):null}catch{}if(!r.ok)throw Error(d?.message||d?.hint||txt||"Erreur HTTP "+r.status);return d}finally{clearTimeout(t)}}
function save(){localStorage.setItem("dhCart",JSON.stringify(S.cart))} function total(){return S.cart.reduce((a,i)=>a+i.price*i.qty,0)}
function badge(){ $("cartCount").textContent=S.cart.reduce((a,i)=>a+i.qty,0);$("cartTotal").textContent=money(total());$("checkoutTotal").textContent=money(total()) }
async function settings(){try{const r=await api("shop_settings?select=whatsapp_number&id=eq.1");if(r?.[0]?.whatsapp_number)S.wa=String(r[0].whatsapp_number).replace(/\D/g,"")}catch{}}
function cats(){return [...new Set(S.products.map(p=>String(p.category||"Autres").trim()).filter(Boolean))]}
function firstProductFor(c){return S.products.find(p=>String(p.category||"Autres").trim()===c&&p.image_url)||S.products.find(p=>p.image_url)}
function categoryData(){return cats().map(c=>({name:c,count:S.products.filter(p=>String(p.category||"Autres").trim()===c).length,img:firstProductFor(c)?.image_url||""}))}
function navigate(page,cat){S.page=page;if(cat!==undefined)S.cat=cat;document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$("page-"+page)?.classList.add("active");document.querySelectorAll("[data-page]").forEach(x=>x.classList.toggle("active",x.dataset.page===page));window.scrollTo({top:0,behavior:"smooth"});history.replaceState(null,"","#"+page);if(page==="boutique"){renderCategories();filter()}closeMenu()}
function renderCategories(){const data=categoryData();$("homeCategories").innerHTML=data.map(c=>`<button class="home-cat" data-cat-home="${esc(c.name)}">${c.img?`<img src="${esc(c.img)}" alt="${esc(c.name)}">`:""}<span>${esc(c.name)}</span><b>→</b></button>`).join("");$("categoryTabs").innerHTML=`<button class="category-tab ${S.cat==="all"?"active":""}" data-cat="all">Tout</button>`+data.map(c=>`<button class="category-tab ${S.cat===c.name?"active":""}" data-cat="${esc(c.name)}">${esc(c.name)}</button>`).join("");$("sideCategories").innerHTML=data.map(c=>`<button data-side-cat="${esc(c.name)}">› <span>${esc(c.name)}</span></button>`).join("");document.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>{S.cat=b.dataset.cat;renderCategories();filter()});document.querySelectorAll("[data-cat-home]").forEach(b=>b.onclick=()=>navigate("boutique",b.dataset.catHome));document.querySelectorAll("[data-side-cat]").forEach(b=>b.onclick=()=>navigate("boutique",b.dataset.sideCat))}
function filter(){let a=[...S.products];if(S.cat!=="all")a=a.filter(p=>String(p.category||"Autres").trim()===S.cat);if(S.q)a=a.filter(p=>`${p.name} ${p.description||""} ${p.category||""}`.toLowerCase().includes(S.q.toLowerCase()));if(S.sort==="price-asc")a.sort((x,y)=>x.price-y.price);if(S.sort==="price-desc")a.sort((x,y)=>y.price-x.price);if(S.sort==="name")a.sort((x,y)=>String(x.name).localeCompare(String(y.name),"fr"));S.filtered=a;render()}
function img(p){return p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}" loading="lazy">`:`<span>DH</span>`}
function card(p){return `<article class="card"><div class="pic" data-view="${p.id}">${p.badge?`<em class="badge">${esc(p.badge)}</em>`:""}<button class="heart" aria-label="Favori">♡</button>${img(p)}</div><div class="info"><small>${esc(p.category||"Produit")}</small><h3>${esc(p.name)}</h3><div class="card-bottom"><strong>${money(p.price)}</strong><button class="add" data-add="${p.id}">+</button></div></div></article>`}
function render(){const g=$("productGrid");g.innerHTML=S.filtered.length?S.filtered.map(card).join(""):`<div class="empty">Aucun produit ne correspond à votre recherche.</div>`;bindCards(g);$("productStatus").textContent=`${S.filtered.length} produit${S.filtered.length>1?"s":""} disponible${S.filtered.length>1?"s":""}`;const f=$("featuredGrid");f.innerHTML=S.products.slice(0,4).map(card).join("");bindCards(f)}
function bindCards(root){root.querySelectorAll("[data-add],[data-view]").forEach(el=>el.onclick=e=>{e.stopPropagation();view(el.dataset.add||el.dataset.view)})}
function find(id){return S.products.find(p=>String(p.id)===String(id))}
function variantList(v){if(Array.isArray(v))return v.map(x=>String(x).trim()).filter(Boolean);if(typeof v!=="string")return[];try{const a=JSON.parse(v);if(Array.isArray(a))return a.map(x=>String(x).trim()).filter(Boolean)}catch{}const s=v.trim();if(/^\d+(?:\.\s*\d+)+$/.test(s))return s.split(/\s*\.\s*/).map(x=>x.trim()).filter(Boolean);return s.split(/[,;\n|/]+/).map(x=>x.trim()).filter(Boolean)}
function variantOptions(p){const sizes=variantList(p.sizes),colors=variantList(p.colors);let h="";if(sizes.length)h+=`<label class="variant-label">Taille<select id="modalSize"><option value="">Choisir une taille</option>${sizes.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join("")}</select></label>`;if(colors.length)h+=`<label class="variant-label">Couleur<select id="modalColor"><option value="">Choisir une couleur</option>${colors.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join("")}</select></label>`;return h}
function add(id,size="",color=""){const p=find(id);if(!p)return;const key=`${p.id}|${size}|${color}`,i=S.cart.find(x=>x.key===key);if(i)i.qty++;else S.cart.push({key,id:p.id,name:p.name,price:Number(p.price),image_url:p.image_url||"",qty:1,size,color});save();cart();openCart()}
function cart(){const b=$("cartItems");b.innerHTML=S.cart.length?S.cart.map(i=>`<div class="row"><div class="thumb">${i.image_url?`<img src="${esc(i.image_url)}">`:"DH"}</div><div><h4>${esc(i.name)}</h4><small>${money(i.price)}${i.size?`<br>Taille : ${esc(i.size)}`:""}${i.color?`<br>Couleur : ${esc(i.color)}`:""}</small><div class="qty"><button data-m="${esc(i.key)}">−</button><b>${i.qty}</b><button data-p="${esc(i.key)}">+</button></div></div><button class="remove" data-r="${esc(i.key)}">Supprimer</button></div>`).join(""):`<div class="empty">Votre panier est vide.</div>`;b.querySelectorAll("[data-m]").forEach(x=>x.onclick=()=>qty(x.dataset.m,-1));b.querySelectorAll("[data-p]").forEach(x=>x.onclick=()=>qty(x.dataset.p,1));b.querySelectorAll("[data-r]").forEach(x=>x.onclick=()=>remove(x.dataset.r));badge()}
function qty(key,d){const i=S.cart.find(x=>x.key===key);if(!i)return;i.qty+=d;if(i.qty<=0)remove(key);else{save();cart()}}function remove(key){S.cart=S.cart.filter(x=>x.key!==key);save();cart()}
function openCart(){$("cartDrawer").classList.add("open");$("overlay").classList.add("open")}function closeCart(){$("cartDrawer").classList.remove("open");$("overlay").classList.remove("open")}
function view(id){const p=find(id);if(!p)return;$('modalContent').innerHTML=`<div class="modalProduct"><div class="modal-photo">${img(p)}</div><div class="modal-info"><small>${esc(p.category||"PRODUIT")}</small><h2>${esc(p.name)}</h2><p>${esc(p.description||"Article sélectionné par DH Shop & Delivery.")}</p><h3>${money(p.price)}</h3><span class="stock">Disponible en stock</span>${variantOptions(p)}<button class="gold-btn full" id="modalAdd">Ajouter au panier</button></div></div>`;$("modalAdd").onclick=()=>{const size=$("modalSize")?.value||"",color=$("modalColor")?.value||"";if($("modalSize")&&!size)return alert("Veuillez choisir une taille.");if($("modalColor")&&!color)return alert("Veuillez choisir une couleur.");$("productModal").classList.remove("open");add(id,size,color)};$("productModal").classList.add("open")}
function makeRef(){return"DH-"+Date.now().toString().slice(-8)}
async function order(e){e.preventDefault();if(!S.cart.length)return alert("Votre panier est vide.");const m=$("checkoutMessage"),btn=e.submitter;btn.disabled=true;m.textContent="Enregistrement…";const ref=makeRef(),o={customer_name:$("customerName").value.trim(),phone:$("customerPhone").value.trim(),address:$("customerAddress").value.trim(),items:S.cart,total:total(),payment_method:$("paymentMethod").value,status:"Nouvelle",reference:ref};try{await api("orders",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify(o)});const lines=S.cart.map(i=>`• ${i.name}${i.size?` — Taille ${i.size}`:""}${i.color?` — ${i.color}`:""} x${i.qty} — ${money(i.price*i.qty)}`).join("\n"),text=`🛍️ *NOUVELLE COMMANDE — DH SHOP & DELIVERY*\n\nRéférence : *${ref}*\nNom : ${o.customer_name}\nTéléphone : ${o.phone}\nAdresse : ${o.address}\nPaiement : ${o.payment_method}\n\n${lines}\n\n*TOTAL : ${money(o.total)}*`,wa=`https://wa.me/${S.wa}?text=${encodeURIComponent(text)}`;S.cart=[];save();cart();$("checkoutForm").reset();m.innerHTML=`✅ Commande enregistrée : <b>${ref}</b><br><small>Conservez cette référence pour suivre votre commande.</small><br><a class="gold-btn" target="_blank" href="${wa}">Continuer sur WhatsApp</a>`}catch(x){m.textContent="❌ "+(x.message||"Erreur")}finally{btn.disabled=false}}
async function track(e){e.preventDefault();const v=$("trackingInput").value.trim().toUpperCase(),r=$("trackingResult");r.textContent="Recherche…";if(!/^DH-[A-Z0-9]+$/.test(v))return void(r.textContent="Entrez une référence comme DH-07048624.");try{const q=await fetch(URL+"/rest/v1/rpc/track_order",{method:"POST",headers:{apikey:KEY,Authorization:"Bearer "+KEY,"Content-Type":"application/json"},body:JSON.stringify({p_reference:v})});const a=await q.json();if(!q.ok)throw Error();r.innerHTML=Array.isArray(a)&&a.length?`<strong>Commande ${esc(a[0].reference)}</strong><br>Statut : <b>${esc(a[0].status||"En traitement")}</b><br><small>${new Date(a[0].created_at).toLocaleString("fr-FR")}</small>`:"Commande introuvable."}catch{r.textContent="Impossible de vérifier la commande."}}
function openMenu(){$("sideMenu").classList.add("open");$("drawerBackdrop").classList.add("open")}function closeMenu(){$("sideMenu").classList.remove("open");$("drawerBackdrop").classList.remove("open")}
function hero(){const first=S.products.find(p=>p.image_url)?.image_url||"";const slides=[{img:"assets/hero-femme.jpg",tag:"QUALITÉ • STYLE • NOUVEAUTÉS",title:"Votre style, votre signature.",text:"De belles nouveautés, de bons prix et la livraison chez vous, sans vous déplacer."},{img:"assets/hero-homme.jpg",tag:"MODE • ÉLÉGANCE • SPORT",title:"Choisissez. Commandez. Recevez.",text:"Chaussures, vêtements, sacs, accessoires et bien plus dans votre boutique DH."},{img:first,tag:"DH SHOP & DELIVERY",title:"Le meilleur du moment, au bon prix.",text:"Découvrez nos produits disponibles et commandez facilement."}].filter(x=>x.img);$("heroSlides").innerHTML=slides.map((s,i)=>`<article class="hero-slide ${i===0?"active":""}"><img src="${esc(s.img)}"><div class="hero-shade"></div><div class="hero-copy"><span>${esc(s.tag)}</span><h1>${esc(s.title)}</h1><p>${esc(s.text)}</p><button class="gold-btn" data-page="boutique">Découvrir la boutique <b>→</b></button></div></article>`).join("");$("heroDots").innerHTML=slides.map((_,i)=>`<button data-hero-dot="${i}" class="${i===0?"active":""}"></button>`).join("");let n=0;const show=i=>{n=(i+slides.length)%slides.length;document.querySelectorAll(".hero-slide").forEach((x,j)=>x.classList.toggle("active",j===n));document.querySelectorAll("[data-hero-dot]").forEach((x,j)=>x.classList.toggle("active",j===n))};$("heroPrev").onclick=()=>show(n-1);$("heroNext").onclick=()=>show(n+1);document.querySelectorAll("[data-hero-dot]").forEach(x=>x.onclick=()=>show(Number(x.dataset.heroDot)));setInterval(()=>show(n+1),7000)}
async function init(){document.querySelectorAll("[data-page]").forEach(x=>x.onclick=()=>navigate(x.dataset.page));$("menuBtn").onclick=openMenu;$("closeMenu").onclick=closeMenu;$("drawerBackdrop").onclick=closeMenu;document.querySelectorAll("[data-open-cart]").forEach(x=>x.onclick=()=>{closeMenu();openCart()});$("cartBtn").onclick=openCart;$("bottomCart").onclick=e=>{e.preventDefault();openCart()};$("closeCart").onclick=closeCart;$("overlay").onclick=closeCart;$("closeProductModal").onclick=()=>$("productModal").classList.remove("open");$("closeCheckoutModal").onclick=()=>$("checkoutModal").classList.remove("open");$("checkoutBtn").onclick=()=>{if(!S.cart.length)return alert("Votre panier est vide.");closeCart();$("checkoutModal").classList.add("open")};$("checkoutForm").onsubmit=order;$("trackingForm").onsubmit=track;$("searchInput").oninput=e=>{S.q=e.target.value;filter()};$("clearSearch").onclick=()=>{$("searchInput").value="";S.q="";filter()};$("sortSelect").onchange=e=>{S.sort=e.target.value;filter()};cart();await settings();$("contactPhoneText").textContent="+"+S.wa;$("contactWhatsapp").href=`https://wa.me/${S.wa}`;$("contactPhone").href=`tel:+${S.wa}`;try{const r=await api("products?select=*&order=created_at.desc");S.products=(r||[]).filter(p=>p.available!==false&&Number(p.stock??1)>0)}catch{S.products=[]}renderCategories();filter();hero();const hash=location.hash.slice(1);if(["boutique","suivi","contact"].includes(hash))navigate(hash);else navigate("accueil")}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
