const CONFIG={supabaseUrl:"https://ocmvthymdjkrhmdyieim.supabase.co",supabaseKey:"sb_publishable_OnchBsvLE3RVA-EualXSSA_pfVvFpTW",whatsappNumber:"22792617092",currency:"FCFA"};
const state={products:[],cart:JSON.parse(localStorage.getItem("dh_cart")||"[]")};const $=s=>document.querySelector(s);const money=n=>new Intl.NumberFormat("fr-FR").format(n)+" "+CONFIG.currency;const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
async function load(){try{const r=await fetch(CONFIG.supabaseUrl+"/rest/v1/products?select=*&available=eq.true&order=created_at.desc",{headers:{apikey:CONFIG.supabaseKey,Authorization:"Bearer "+CONFIG.supabaseKey}});if(!r.ok)throw 0;state.products=await r.json();cats();render()}catch(e){$("#grid").innerHTML='<div class="empty">Impossible de charger les produits.</div>'}}
function cats(){let c=[...new Set(state.products.map(p=>p.category).filter(Boolean))];$("#category").innerHTML='<option value="all">Toutes les catégories</option>'+c.map(x=>`<option>${esc(x)}</option>`).join("")}
function render(){let q=$("#search").value.toLowerCase(),c=$("#category").value;let a=state.products.filter(p=>(c==="all"||p.category===c)&&(!q||(`${p.name} ${p.description} ${p.category}`).toLowerCase().includes(q)));$("#grid").innerHTML=a.length?a.map(p=>`<article class="card"><div class="pic">${p.badge?`<span class="badge">${esc(p.badge)}</span>`:""}${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}">`:'<span class="placeholder">DH</span>'}</div><div class="info"><span class="cat">${esc(p.category||"Boutique")}</span><h3>${esc(p.name)}</h3><div class="price">${money(p.price)}</div><div class="actions"><button onclick="detail(${p.id})">Détails</button><button onclick="add(${p.id})">Ajouter</button></div></div></article>`).join(""):'<div class="empty">Aucun produit trouvé.</div>'}
window.detail=id=>{let p=state.products.find(x=>x.id===id);$("#modalContent").innerHTML=`<h2>${esc(p.name)}</h2><p>${esc(p.description)}</p><h3>${money(p.price)}</h3><button class="btn" onclick="add(${p.id});closeModal()">Ajouter au panier</button>`;$("#modal").classList.remove("hidden")};window.closeModal=()=>$("#modal").classList.add("hidden");
window.add=id=>{let p=state.products.find(x=>x.id===id),x=state.cart.find(x=>x.id===id);x?x.qty++:state.cart.push({id:p.id,name:p.name,price:p.price,qty:1});save();openCart()};window.change=(i,d)=>{state.cart[i].qty+=d;if(state.cart[i].qty<1)state.cart.splice(i,1);save()};window.removeItem=i=>{state.cart.splice(i,1);save()};function save(){localStorage.setItem("dh_cart",JSON.stringify(state.cart));cart()}
function cart(){$("#cartCount").textContent=state.cart.reduce((a,x)=>a+x.qty,0);$("#cartTotal").textContent=money(state.cart.reduce((a,x)=>a+x.price*x.qty,0));$("#cartItems").innerHTML=state.cart.length?state.cart.map((x,i)=>`<div class="row"><div class="thumb">DH</div><div><b>${esc(x.name)}</b><div>${money(x.price)}</div><div class="qty"><button onclick="change(${i},-1)">−</button>${x.qty}<button onclick="change(${i},1)">+</button></div></div><button onclick="removeItem(${i})" class="x">×</button></div>`).join(""):'<div class="empty">Votre panier est vide.</div>'}
function openCart(){$("#drawer").classList.add("open");$("#drawerBack").classList.remove("hidden")}function closeCart(){$("#drawer").classList.remove("open");$("#drawerBack").classList.add("hidden")}
function checkout(){if(!state.cart.length)return alert("Votre panier est vide.");$("#modalContent").innerHTML=`<h2>Finaliser la commande</h2><p>Paiement à la livraison</p><form id="form" class="form"><input name="name" placeholder="Nom complet" required><input name="phone" placeholder="Téléphone" required><textarea name="address" placeholder="Adresse de livraison" required></textarea><button class="btn" type="submit">Confirmer la commande</button></form>`;$("#modal").classList.remove("hidden");closeCart();$("#form").onsubmit=send}
async function send(e){e.preventDefault();let f=new FormData(e.target),items=state.cart.map(x=>({id:x.id,name:x.name,price:x.price,quantity:x.qty})),total=items.reduce((a,x)=>a+x.price*x.quantity,0),order={customer_name:f.get("name"),phone:f.get("phone"),address:f.get("address"),items,total,payment_method:"Paiement à la livraison",status:"nouvelle"};try{await fetch(CONFIG.supabaseUrl+"/rest/v1/orders",{method:"POST",headers:{"Content-Type":"application/json",apikey:CONFIG.supabaseKey,Authorization:"Bearer "+CONFIG.supabaseKey},body:JSON.stringify(order)})}catch(_){}let msg=`Bonjour DH Shop & Delivery 👋\n\nJe souhaite passer une commande.\n\n${items.map(x=>"- "+x.name+" x"+x.quantity+" : "+money(x.price*x.quantity)).join("\n")}\n\nTotal : ${money(total)}\nPaiement : Paiement à la livraison\n\nNom : ${f.get("name")}\nTéléphone : ${f.get("phone")}\nAdresse : ${f.get("address")}`;window.open("https://wa.me/"+CONFIG.whatsappNumber+"?text="+encodeURIComponent(msg),"_blank");state.cart=[];save();closeModal()}
$("#cartBtn").onclick=openCart;$("#closeCart").onclick=closeCart;$("#drawerBack").onclick=closeCart;$("#checkout").onclick=checkout;document.querySelector(".backdrop").onclick=closeModal;$("#search").oninput=render;$("#category").onchange=render;$("#year").textContent=new Date().getFullYear();cart();load();
